### ISSUE TITLE
The inverse of the inverse

### ISSUE THREAD

**Issue by densjac** [elibtronic/pythonMCS#2]
I was trying to expand your code for Hamming(15,11) and I found out that your code wasn't being consistent on some cases. For Hamming (8,4) isn't too notorious but for bigger codes it seems to occur more frequently.

Because your are casting to int, the inverse of the inverse isn't the same as the original for S all the time.

I made some verification with the determinant of the inverse of S and compared the S == S.I.I when generating S to make sure that the matrix will always work.

**Comment by elibtronic** [comment]
Wow. Nice catch. Not sure if I'll ever return to the code but if I do I'll examine this problem.
